### ISSUE TITLE
Social transform output has wrong tag

### ISSUE THREAD

**Issue by FarallonWest** [reconurge/flowsint#41]
Social transform output is social_profile instead of button for social. 

<img width="117" height="524" alt="Image" src="https://github.com/user-attachments/assets/bbcb6837-d5b7-4f0a-b7a0-37cf8af70ff5" />

**Comment by dextmorgn** [comment]
Should be fixed with [dba97be](https://github.com/reconurge/flowsint/commit/dba97be684712f27f2408d97c45ef8cc44a307bf). 

For changes to appear, please remove `nodes-display-settings` from your localStorage.

**Comment by FarallonWest** [comment]
I removed the file from localstorage with this path: flowsint › flowsint-app › stores > node-display-settings.ts

but it did not fix the problem. I exited, spun down Docker and restarted. I got this error (picture). Was able to re-enter the investigative space by going to the local url manually.

I am fairly certain this is my own user error. 

<img width="867" height="428" alt="Image" src="https://github.com/user-attachments/assets/585ffbe5-89ca-4b30-a370-5afb73f6d330" />

**Comment by dextmorgn** [comment]
Sorry this is not what I meant, you need to remove object `nodes-display-settings` from your browser's localStorage. 

So:

1. first put back `flowsint/flowsint-app/stores/node-display-settings.ts`
2. on [http://localhost:5173](http://localhost:5173), right click on the page and click on inspect. Then in the `storage` (or `Application` on Chrome) tab, you'll see the section with `localStorage`, click on the `nodes-display-settings` and delete it, it will be re-generated afterwards

Let me know if you need more help !

**Comment by FarallonWest** [comment]
It is moved back and I cannot find the localStorage. This is the closest thing I have.

<img width="940" height="287" alt="Image" src="https://github.com/user-attachments/assets/22566aca-0fe4-4582-9e3a-00fee4e67a58" />

**Comment by dextmorgn** [comment]
Good, so it's not there (it's going to be re-generated if you run 'randomize colors' in the settings, but you don't need to worry about it). You should not have the problem anymore. Can you confirm your app has restarted correctly and tag `social_profile` is displaying correctly ?
