### ISSUE TITLE
No create user

### ISSUE THREAD

**Issue by KIKIPEN** [reconurge/flowsint#55]
<img width="609" height="455" alt="Image" src="https://github.com/user-attachments/assets/23ff39ff-77be-40ed-b01d-0d26711cb091" />

**Comment by dextmorgn** [comment]
Hello,

Could you run `docker ps` and make sure all services are running ?

**Comment by wpavlis** [comment]
I have the same problem. All 4 services are UP

**Comment by dextmorgn** [comment]
hey @wpavlis thanks for the feedback. Which setup are you running ? dev or prod ?

**Comment by wpavlis** [comment]
I am right after installation, it is the first step. it is only a development environment
maybe it's a problem with a busy port

**Comment by dextmorgn** [comment]
Thanks. Can you run `docker logs flowsint-api-dev` ?
Ah, do you have an other service using port 5001 ?

**Comment by pelaohcx** [comment]
I have the same problem. 

<img width="511" height="574" alt="Image" src="https://github.com/user-attachments/assets/c3d0955a-b861-4e00-b6e9-cc25a0e8c84a" />

<img width="1642" height="211" alt="Image" src="https://github.com/user-attachments/assets/ab625bd0-6f0c-4b8f-b0b3-946ef86752df" />

**Comment by dextmorgn** [comment]
Hey @pelaohcx, do you have any errors in the web console ?

**Comment by pelaohcx** [comment]
> Hey [@pelaohcx](https://github.com/pelaohcx), do you have any errors in the web console ?
only this

<img width="1660" height="751" alt="Image" src="https://github.com/user-attachments/assets/fc1a9690-1493-40ca-9159-0f4ade460010" />

<img width="1646" height="851" alt="Image" src="https://github.com/user-attachments/assets/1b52fa91-ee25-4fdc-a529-6c7cc726c04e" />

<img width="1626" height="802" alt="Image" src="https://github.com/user-attachments/assets/4e70ee5f-bf26-4005-8d03-c3609e8406e3" />

<img width="1220" height="264" alt="Image" src="https://github.com/user-attachments/assets/b518fd3c-4c29-4128-999a-4b70c1d5b5b3" />

**Comment by dextmorgn** [comment]
and `docker -f logs flowsint-api-prod` ?

**Comment by pelaohcx** [comment]
> and `docker -f logs flowsint-api-prod` ?

Yes, this one did have errors.

<img width="946" height="842" alt="Image" src="https://github.com/user-attachments/assets/74a5359b-5309-4d0f-9f44-68fb556d3aaa" />

**Comment by dextmorgn** [comment]
Thanks I'll try to reproduce and let you know.

**Comment by dextmorgn** [comment]
@KIKIPEN, @pelaohcx, @wpavlis I've been able to reproduce the bug. You can re-run `make dev` or `make prod` (a second time) again and you should be able to access the app now. The bug happens on the first instancing of the app, while migrating the db. 

You should be able to still use it after running `make dev` or `make prod` a second time while I work on a fix. Thanks for raising this issue.

**Comment by dextmorgn** [comment]
It should now be fixed with [45d51dd](https://github.com/reconurge/flowsint/commit/45d51dd2a8c4a85a711970dc4510b93639c9237d)

**Comment by pelaohcx** [comment]
> It should now be fixed with [45d51dd](https://github.com/reconurge/flowsint/commit/45d51dd2a8c4a85a711970dc4510b93639c9237d)

The error persists, but now with letters and colors in the fields.

<img width="659" height="529" alt="Image" src="https://github.com/user-attachments/assets/4f4891ae-3d71-4aca-acf7-1008d78c9d51" />

**Comment by dextmorgn** [comment]
woops I left react scan on. I removed it and keep investigating

**Comment by Ntn10** [comment]
Excellent tool, my friend. It looks very promising. Like the previous user, I am experiencing the same issue when registering a user. It would be great if you could fix it.

**Comment by dextmorgn** [comment]
Could you run:

```bash
git pull --rebase
# then
make clean && make prod
```

And tell me if you still get the same issue ?

**Comment by Ntn10** [comment]
<img width="535" height="617" alt="Image" src="https://github.com/user-attachments/assets/007c2554-8ae8-4c38-b429-0ebf8eea0ae6" />

**Comment by Ntn10** [comment]
I have followed all the steps from the beginning and the error persists.

**Comment by pelaohcx** [comment]
> make clean && make prod

done, but the error persists, but without the colors in the fields

<img width="754" height="673" alt="Image" src="https://github.com/user-attachments/assets/59bce48f-b103-4931-8c4f-4985619b92fe" />

**Comment by dextmorgn** [comment]
Can you guys send me the results of `docker -f logs flowsint-api-prod` ?

This is very likely related to the api.

**Comment by blackdarksy** [comment]
![IMG_20251115_145041.jpg](https://github.com/user-attachments/assets/ae8e31d2-3a42-40f9-847f-b6ffdd185475)


I think some issues with request is blocked

**Comment by Qu4rk0** [comment]
Hi, I was working on fixing this yesterday, and this is indeed the issue. I'm not part of the team, but I managed to find the solution. 

This happens because we're targeting localhost.

 If the tool is installed on a different machine, not our PC/laptop, it won't reach localhost. Here's the command to fix this: 

```
find ~/flowsint -type f -name ".env" -exec sed -i 's|127.0.0.1:5001|<your.ip>:5001|g' {} \;
``` 

and then:

```
cd ~/flowsint
docker compose -f docker-compose.prod.yml down
docker compose -f docker-compose.prod.yml build --no-cache app
docker compose -f docker-compose.prod.yml up -d
```

Do all of this with the tool owner's permissions, and please validate the solution. It worked for me. 

Another solution could be to use Firefox and change the request IP address in the developer tools, pointing the request to the IP address where your Flowsint is hosted. 

I hope this helps 🙌.
> ![IMG_20251115_145041.jpg](https://github.com/user-attachments/assets/ae8e31d2-3a42-40f9-847f-b6ffdd185475)
> 
> 
> I think some issues with request is blocked 
>

**Comment by blackdarksy** [comment]
Thank u it's working now
> Hi, I was working on fixing this yesterday, and this is indeed the issue. I'm not part of the team, but I managed to find the solution. 
> 
> This happens because we're targeting localhost.
> 
>  If the tool is installed on a different machine, not our PC/laptop, it won't reach localhost. Here's the command to fix this: 
> 
> ```
> find ~/flowsint -type f -name ".env" -exec sed -i 's|127.0.0.1:5001|<your.ip>:5001|g' {} \;
> ``` 
> 
> and then:
> 
> ```
> cd ~/flowsint
> docker compose -f docker-compose.prod.yml down
> docker compose -f docker-compose.prod.yml build --no-cache app
> docker compose -f docker-compose.prod.yml up -d
> ```
> 
> Do all of this with the tool owner's permissions, and please validate the solution. It worked for me. 
> 
> Another solution could be to use Firefox and change the request IP address in the developer tools, pointing the request to the IP address where your Flowsint is hosted. 
> 
> I hope this helps 🙌.
> > ![IMG_20251115_145041.jpg](https://github.com/user-attachments/assets/ae8e31d2-3a42-40f9-847f-b6ffdd185475)
> > 
> > 
> > I think some issues with request is blocked 
> > 
> 
>

**Comment by dextmorgn** [comment]
@blackdarksy thank you for figuring this out ! Indeed the documentation doesn't cover self hosting for now. 

I'll create some docs covering this very soon.

**Comment by KIKIPEN** [comment]
I try cmt: 
find ~/flowsint -type f -name ".env" -exec sed -i 's|127.0.0.1:5001|<your.ip>:5001|g' {} \;
docker compose -f docker-compose.prod.yml down
docker compose -f docker-compose.prod.yml build --no-cache app
docker compose -f docker-compose.prod.yml up -d
and ressult:
<img width="607" height="607" alt="Image" src="https://github.com/user-attachments/assets/5970bde1-18d4-45c4-a9e0-47c56f6868de" />

**Comment by Twi1ight** [comment]
> <your.ip>

means your real ip address

**Comment by KIKIPEN** [comment]
Thanks I try again

**Comment by KIKIPEN** [comment]
So result
<img width="1502" height="688" alt="Image" src="https://github.com/user-attachments/assets/b87c50be-5cbe-45bf-9de9-d0b5d0027a2e" />

**Comment by dextmorgn** [comment]
You need to replace `<your.ip>` with your actual IP address. 

This is a placeholder for you to replace with something like `192.168.x.x`

**Comment by KIKIPEN** [comment]
From soure or cmd. I try with cmd

**Comment by dextmorgn** [comment]
retry with : 

```bash
find ~/flowsint -type f -name ".env" -exec sed -i 's|127.0.0.1:5001|192.168.x.x:5001|g' {} ;
docker compose -f docker-compose.prod.yml down
docker compose -f docker-compose.prod.yml build --no-cache app
docker compose -f docker-compose.prod.yml up -d
```

But make sure you replace the part with `192.168.x.x` with your actual server address.

**Comment by KIKIPEN** [comment]
I try the same cmd and no create user

**Comment by dextmorgn** [comment]
Same error ?

**Comment by KIKIPEN** [comment]
Exactly.
<img width="1043" height="503" alt="Image" src="https://github.com/user-attachments/assets/0472b908-65e1-4afc-bd4f-1b0cc9e632f5" />

**Comment by dextmorgn** [comment]
Well it seems your IP is not correctly configured, as the message error shows incorrect url. Meaning your app was not rebuilt with latest changes or your .env files are still not configured properly; can you show output of: 

```
cat ./flowsint-app/.env
```

Feel free to obfuscate any credential before sending

**Comment by KIKIPEN** [comment]
I changed the .env config and created the user to login. Thank you very much!
